### ISSUE TITLE
Provide option to insert Video Clip as an item

### ISSUE THREAD

**Issue by matthiku** [matthiku/cSpot#141]
In order to minimize database table changes, we could use a "song" item (which can contain a link to a YouTube video) and add a code into the "key" field of the plan item (e.g. "{play_video}") which will be interpreted by the presentation view to embed the linked video into the presentation!
(Lyrics and Sheetmusic Presentations need to ignore that key!)
### Work Plan:
- [x] modify document.ready.js to prepare a slide for video embedding
- [x] modify presentation.js to ignore that key for chords and sheet music
- [x] modify same to embed linked video into Presentation View when _item->key == {show_video}_
- [x] modify Song List View to present a menu when clicking on "Add a new item" button. Menu will offer: Song, InfoScreen or VideoPlayer
- [x] Modify SongController to provide for those new "song" types
- [x] use field "subtitle" to indicate whether the song is actually a "infoscreen" or a "video" item

**Comment by matthiku** [comment]
resolved in a "minimalistic" way so far.....

**Comment by matthiku** [comment]
changes for this issue introduced a bug that prevents the show of images and bible verses

**Comment by matthiku** [comment]
bug resolved
