### ISSUE TITLE
Provide option to add notes and items for leader's eyes only

### ISSUE THREAD

**Issue by matthiku** [matthiku/cSpot#147]
### Phase 1: Add Ability to Mark Item "For Leaders Eyes Only"
- [x] Add field to Items table indicating that this item is 'for leaders eyes only'
- [x] Add button or checkbox on Items List (Plan Detail) page to make item 'for leaders eyes only'
- [x]  Add button or checkbox on Items Detail page to make item 'for leaders eyes only'

### Phase 2: Provide Feature to Add Individual, Personal Notes to Items
- [x]  Add new table "private_notes" with item_id and owner field (user_id) so that only the creator of the notes can see them
- [x] link to new table from item Model
- [x] Add field on Item Details page
- [x] Add link to tooltip for direct manipulation or make it editable via editable plugin
- [x] Show private notes as popup tooltip in Plan Details View's item listing
- [x] show private notes as popup tooltip on the chords or sheetmusic presentation pages
