### ISSUE TITLE
Song Details: Add file upload capability

### ISSUE THREAD

**Issue by matthiku** [matthiku/cSpot#62]
A song could have several file items (e.g. sheetmusic with different keys) so we need to create a new table and add a field to the songs - file_id
#### Todo: 
- [x] show as thumbnails (link to fullsize) on the songs detail page

- [x] Ability to delete files

- [x] Show presence of files in Song List and Items list (Plan Detail)

- [x] Show in the "Sheet Music" tab of the Item Details page

**Comment by matthiku** [comment]
File upload and database relations done.

Todo: show as thumbnails on the songs detail page

**Comment by matthiku** [comment]
All done.
